### ISSUE TITLE
i18n.languages renders different on initial pageload vs refresh or manual language switching?

### ISSUE THREAD

**Issue by hdehal** [i18next/i18next-browser-languageDetector#219]
## 🐛 Bug Report

On **initial pageload**, I am trying to detect the current language, e.g.:
`const currentLang = (Array.isArray(i18n.languages)) ? i18n.languages[0] : i18n.languages;`

A console.log of `console.log(i18n.languages)` reveals:
`Array [ "en-US", "en" ]`

And `{currentLang}` renders accordingly as `en-US` on initial pageload. 

However, **on page refresh or if I manually switch the language** using `onClick={() => changeLanguage('en')}` it switches to `en` instead of `en-US.`

A console.log of `console.log(i18n.languages)` now reveals (after refresh):
`Array [ "en" ]`

Same issue with other languages. Why is it behaving inconsistently on initial pageload vs refreshes or manual language switching?

Apologies if I'm overlooking something simple. Thanks!

## Your Environment

- macOS Firefox and Chrome 

```
i18next: ^19.6.2
i18next-browser-languagedetector: ^5.0.0,
react: ^16.13.1,
```

**Comment by jamuhl** [comment]
because the detector detects your locale which is set by you to `en-US` you set the language to `en` (so there is no magic guessing you mean en-US or en-GB of en-whatever)...

you can set `load: 'languageOnly` to enforce only taking language part and omit the region from a detected / set language. Or use the supportedLanguages to set what is allowed to load

**Comment by hdehal** [comment]
Thanks for the quick response! 

Per your advice I was able to find `load: 'languageOnly'` and put it in my init in i18n.js per https://www.i18next.com/overview/configuration-options#languages-namespaces-resources 

Looks like it's working perfectly. Thanks!
