### ISSUE TITLE
Navigator detector returns array of languages

### ISSUE THREAD

**Issue by gitohyeah** [i18next/i18next-browser-languageDetector#251]
I'm on Chrome, Windows 10, react-typescript app.

We had big trouble with the languageDetector not working for our clients. The had Windows in 'cz' (czech language), chrome browser set to 'cz', yet when they first open our app, the languageDetector sets it to 'en'. After forking languageDetector, we found out that the output of navigator detection (in the loop at i18nextBrowserLanguageDetector.js, line 390) is an array of languages. It seems pretty random in order, something like this: 

`['cs', 'sk', 'en', 'cs-CZ', 'cs']`

The problem is, sometimes the first language in the array that our app supports is 'en', even though there are multiple 'cs' in the array. And since the 'en' is before them, english gets applied. 

We have no idea where the 'en' could come from in the browser, since browser has just single set language ('cs' in this case). Neither why does it return so many languages from the navigator object.

Is this a bug, or just confusing behaviour? Is there some config to fix this, or do we have to rework how the navigator lookup works?

**Comment by gitohyeah** [comment]
Yes but that's not what I ment, the 'navigator' detector on it's own returns an array of languages.
My chrome is now set to 'sk' language, but navigator.Languages returns this: 

`['sk', 'hu', 'cs', 'en', 'cs-CZ']`

I'm console-logging all detectors, and no other detector detects anything (after previously deleting all local storage data), only navigator returns an array of languages, even if 'sk' is the only language of my chrome browser. This causes trouble as mentioned in the original post, as I have no idea where the other browser languages come from, and they sometimes result in i18next setting the wrong language for the user.

In the example above, our app supports 'cs', 'en', 'hu', fallback language is 'cs'. Consider browser in unsupported 'sk'. Since 'sk' is not supported, i18next should set the language to the fallback 'cs'. But becase the browser returns array of multiple languages, it instead picks another supported language from the array, in this example it's 'hu'. This is undesired behaviour.

In my fork I fixed 'navigator' detector to return only the main selected language of the browser, which is the behaviour we want.

**Comment by adrai** [comment]
This means `navigator.languages` returns all those languages.
Which languages do you see on this page: chrome://settings/languages ?

For example, If I check on my chrome browser I see:
![image](https://user-images.githubusercontent.com/1086194/149489792-fa37312c-1ac6-48c9-9cf0-5463f777cd88.png)
and `navigator.languages` looks like this: `['it-IT', 'it', 'de', 'en-US', 'en']`
![image](https://user-images.githubusercontent.com/1086194/149489878-02073d1a-ace7-4666-92a8-c4cad05aa150.png)

This library takes what is returned here in the navigator object: https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/browserLookups/navigator.js#L8

So it looks all correct to me.

**Comment by gitohyeah** [comment]
Ok this looks correct, I'm just confused by the resulting behaviour. 

This is our i18next implementation:

` i18n
        .use(LanguageDetector)
        .use(initReactI18next)
        .init({
            resources,
            debug: true,
            detection: {
                order: ['querystring', 'cookie', 'localStorage', 'sessionStorage', 'navigator', 'path', 'subdomain', 'htmlTag'],
                htmlTag: document.body
            },
            supportedLngs: ['cs', 'en', 'hu'],
            nonExplicitSupportedLngs: true,
            fallbackLng: ['cs'],
            interpolation: {
                escapeValue: false
            }
        });`

And still, some users who have 'cs' Windows, 'cs' browser and enter the app for the very first time get their language set to 'en' for some reason. It's a big issue for some of our clients.

**Comment by adrai** [comment]
I suspect their browser languages contains en language somewhere...

**Comment by DavidJohnWilliams** [comment]
Just adding my findings.

The current navigator detector adds all of the browsers supported languages `navigator.languages` (i.e. languages added in the settings by default or by the user) followed by the actual language currently in use `navigator.language`.

The resulting list is of the `navigator.languages` in alphabetical order followed by the `navigator.language` as per the screenshots posted by [adrai](https://github.com/adrai) above.

So with the scenario above it would be something like:

`[ 'it-IT', 'it', 'de', 'en-US', 'en', 'it'IT' ]`

Now imagine that the supported languages are:

`[ 'en', 'en-US', 'de' ]` and the fallback is `'en'`.

In this case the user's current browser display language is not supported, but instead of using the fallback, the language displayed to the user will be `'de'` (German). Which would be a bit odd and unexpected.

A simple way to avoid this is to write a custom detector which only uses `navigator.lanugage` but it feels like that could do with being a built in option.

**Comment by DavidJohnWilliams** [comment]
A simpler way to think about it:

`navigator.languages` represents the list of installed languages.

Just because a language is installed in the browser does it mean that the user would want to see it in that language if you don't support their display language?

Granted this is primarily going to affect users who mess around with languages in their browser e.g. developers. But I think it would be equally confusing for a user if they added a foreign language (e.g. for learning) but suddenly sites start displaying that language instead of the native language or fallback.

So an example:

```js
i18n
    .use(LanguageDetector)
    .use(Backend)
    .use(initReactI18next)
    .init({
        fallbackLng: "en-US",
	backend: {
            ...
	}
    },
    detection: {
        order: [
	    "navigator"
	],
	caches: []
    },
    supportedLngs: ["en-US", "es-MX"]
});
```

The users native language and current browser display setting is `French (Canada)` but they also install `Spanish (Mexico)` in the  browser language settings (for whatever reason).

Using the out of the box settings for navigator detector the site will be shown in Spanish.


To me it doesn't really make sense to just pick the first supported language from the entire list of installed languages. It would be better to use the display language if supported and then the fallback.

Using `navigator.languages` would be best used in conjunction with `nonExplicitSupportedLngs`.

**Comment by jamuhl** [comment]
We can argue back and forth...there are different ways of looking at it:

For me: I can add browser languages and even order them in priority (depending on preference)...so for me it makes sense to pick the highest in the order and not the fallback some dev defined.

So for your sample my native language is french...but I studied in Spain and also talk spanish rather fell...as a french man I hate england so I can't speak any english...so why should I prefer the set fallback of english?

**Comment by adrai** [comment]
> `navigator.languages` represents the list of installed languages.

The [navigator.languages](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/languages) read-only property returns an array of strings representing the user's **preferred** languages.

**Comment by DavidJohnWilliams** [comment]
@jamuhl @adrai 

Both good points, I was just reporting what I found really. It is easy enough to override the behavior with a custom detector anyway.
